Automatically setup shared directory on install

diff --git a/bin/kali b/bin/kali
--- a/bin/kali
+++ b/bin/kali
@@ -49,12 +49,88 @@ _get_ipaddress() {
 		"$netstatus"
 }
 
-cmd_start() {
-	virsh start "$vm_name"
+_send_key() {
+	virsh send-key "$vm_name" $@
 }
 
-cmd_stop() {
-	virsh destroy "$vm_name"
+_restart_ssh() {
+	printf "%s\n" 'Switching to command line...'
+	_send_key KEY_LEFTCTRL KEY_LEFTALT KEY_F1
+	printf "%s\n" 'Restarting SSH daemon on guest...'
+	sleep 1
+	_send_key KEY_S
+	_send_key KEY_U
+	_send_key KEY_D
+	_send_key KEY_O
+	_send_key KEY_SPACE
+	_send_key KEY_S
+	_send_key KEY_Y
+	_send_key KEY_S
+	_send_key KEY_T
+	_send_key KEY_E
+	_send_key KEY_M
+	_send_key KEY_C
+	_send_key KEY_T
+	_send_key KEY_L
+	_send_key KEY_SPACE
+	_send_key KEY_R
+	_send_key KEY_E
+	_send_key KEY_S
+	_send_key KEY_T
+	_send_key KEY_A
+	_send_key KEY_R
+	_send_key KEY_T
+	_send_key KEY_SPACE
+	_send_key KEY_S
+	_send_key KEY_S
+	_send_key KEY_H
+	_send_key KEY_ENTER
+	_send_key KEY_LEFTCTRL KEY_LEFTALT KEY_F7
+	sleep 1
+}
+
+# See [0] for more information.
+# [0] https://www.linux-kvm.org/page/9p_virtio
+_setup_share() {
+	local guestip
+
+	guestip="$(_get_ipaddress)"
+
+	if [ -z "$guestip" ]; then
+		printf "%s\n" "IP address not found, is the domain up?" >&2
+		return 1
+	fi
+
+	printf "%s\n" "Connecting to $guestip..."
+
+	local keymap
+	keymap="$(\
+		localectl status \
+		| grep -i 'X11 Layout' \
+		| cut -d ':' -f 2 \
+	)"
+
+	local hostip
+	hostip="$(\
+		ip addr show dev $ifname \
+		| awk '/inet/ {print $2}' \
+		| cut -d/ -f1 \
+	)"
+
+	printf "%s\n" 'Setting up shared directory...'
+
+	sshpass -p "$ssh_password" ssh \
+		-o UserKnownHostsFile=/dev/null \
+		-o StrictHostKeyChecking=no \
+		"$ssh_username@$guestip" <<-EOF
+			sudo su -c 'mkdir /shared
+			mount -t 9p -o trans=virtio,version=9p2000.L /shared /shared
+			sudo iptables -A INPUT -s $hostip -p tcp --dport 22 -j ACCEPT
+			sudo iptables -A INPUT -p tcp --dport 22 -j DROP'
+			DISPLAY=:0 xrandr --size 1920x1080
+			DISPLAY=:0 setxkbmap $keymap
+			touch ~/.hushlogin
+		EOF
 }
 
 cmd_install() {
@@ -72,6 +148,12 @@ cmd_install() {
 		--virt-type kvm \
 		--network "bridge=$ifname,mac.address=$macaddress" \
 		--noautoconsole
+	sleep 1
+	_send_key KEY_ENTER
+	printf "%s\n" 'Waiting for the machine to boot completely...'
+	sleep 20
+	_restart_ssh
+	_setup_share
 }
 
 _download_cdrom() {
@@ -133,55 +215,13 @@ cmd_gui() {
 
 cmd_clean() {
 	set +e
-	cmd_stop
+	virsh destroy "$vm_name"
 	set -e
 	virsh undefine "$vm_name"
 }
 
 cmd_list() {
 	virsh list --all
-}
-
-# See [0] for more information.
-# [0] https://www.linux-kvm.org/page/9p_virtio
-cmd_share() {
-	local guestip
-
-	guestip="$(_get_ipaddress)"
-
-	if [ -z "$guestip" ]; then
-		printf "%s\n" "IP address not found, is the domain up?" >&2
-		return 1
-	fi
-
-	printf "%s\n" "Connecting to $guestip."
-
-	local keymap
-	keymap="$(\
-		localectl status \
-		| grep -i 'X11 Layout' \
-		| cut -d ':' -f 2 \
-	)"
-
-	local hostip
-	hostip="$(\
-		ip addr show dev $ifname \
-		| awk '/inet/ {print $2}' \
-		| cut -d/ -f1 \
-	)"
-
-	sshpass -p "$ssh_password" ssh \
-		-o UserKnownHostsFile=/dev/null \
-		-o StrictHostKeyChecking=no \
-		"$ssh_username@$guestip" <<-EOF
-			sudo su -c 'mkdir /shared
-			mount -t 9p -o trans=virtio,version=9p2000.L /shared /shared
-			sudo iptables -A INPUT -s $hostip -p tcp --dport 22 -j ACCEPT
-			sudo iptables -A INPUT -p tcp --dport 22 -j DROP'
-			DISPLAY=:0 xrandr --size 1920x1080
-			DISPLAY=:0 setxkbmap $keymap
-			touch ~/.hushlogin
-		EOF
 }
 
 cmd_permissions() {
@@ -199,15 +239,8 @@ cmd="$1"
 _setup_directories
 
 case "$cmd" in
-	start)
-		cmd_start
-		;;
-	stop)
-		cmd_stop
-		;;
 	install)
 		cmd_install
-		cmd_gui
 		;;
 	download)
 		cmd_download
@@ -224,13 +257,10 @@ case "$cmd" in
 	list)
 		cmd_list
 		;;
-	share)
-		cmd_share
-		;;
 	permissions)
 		cmd_permissions
 		;;
 	*)
-		printf "%s\n" "Usage: $0 {start,stop,install,download,ssh,gui,clean,list,share,permissions}" >&2
+		printf "%s\n" "Usage: $0 {install,download,ssh,gui,clean,list,permissions}" >&2
 		exit 1
 esac
