fix: some enhancement following review

diff --git a/internal/scripts/bin/hackenv_fixlabels b/internal/scripts/bin/hackenv_fixlabels
--- a/internal/scripts/bin/hackenv_fixlabels
+++ b/internal/scripts/bin/hackenv_fixlabels
@@ -8,6 +8,16 @@ datahome="$datahome/hackenv"
 
 shared="$(realpath "$datahome/shared")"
 
+printf "Trying to fix SElinux labels...\n" >&2
+
+if ! command -v semanage &> /dev/null; then
+	printf "SElinux coreutils binaries could not be found.\n" >&2
+	command -v yum &> /dev/null &&
+		sudo yum -y install policycoreutils-python-utils ||
+		printf "Exiting.\n" >&2
+	exit 0
+fi
+
 printf "Setting permissions for shared directory...\n" >&2
 
 mkdir -p "$shared"
